### ISSUE TITLE
v0.1.3 Crash à l'ouverture

### ISSUE THREAD

**Issue by juju92** [Oliv4945/jarvis-android-app#10]
Bonjour,

J'ai tenté de lancer l'application v0.1.3 mais ca plante directement au lancement.

Caractèristiques : 
 * LeEco Pro 3
 * 7.1.1 LineageOS 14.1
 * v0.1.3

Fichier de log joint

[error.txt](https://github.com/Oliv4945/jarvis-android-app/files/958441/error.txt)

**Comment by Oliv4945** [comment]
Ok problème trouvé [ici](https://github.com/Oliv4945/jarvis-android-app/blob/master/app/src/main/java/net/iopush/jarvis/MainActivity.java#L138), merci pour le log !

Du coup problème se reproduit chez moi en supprimant les préférences, ce qui est surprenant c'est que j'ai quand même accès aux paramètres après le message d'erreur. Si jamais vous avez aussi la fenêtre de paramètres il suffit de rentrer une adresse de serveur pour éviter ça.

Je corrige ce soir

**Comment by Oliv4945** [comment]
Bonsoir, ça devrait être résolu dans la [v0.1.4](https://github.com/Oliv4945/jarvis-android-app/releases/tag/v0.1.4), merci de me tenir au courant :-)

**Comment by juju92** [comment]
L'appli démarre ! Merci

Je test tout ca et je te fais un retour
