### ISSUE TITLE
Not working microphone button

### ISSUE THREAD

**Issue by Oliv4945** [Oliv4945/jarvis-android-app#12]
From @jean-luc18, [here](https://github.com/Oliv4945/jarvis-android-app/issues/5#issuecomment-298319313)
>sur deux tablettes avec android 4.4.2 ça fonctionne pas à 100%.
le bouton micro est inactif.

Ok c'est normalement résolu via [f14049](f1404927418e53c6cfe5c9790daab10372e669e9), merci. Pourrais-tu confirmer avec la release [v0.2.1](https://github.com/Oliv4945/jarvis-android-app/releases/tag/v0.2.1) ?

> pour faire fonctionner l'appli (v0.2.0) il faut activer la reconnaissance vocale à l'ouverture.
il y a un temps de latente plus long aussi bien pour le retour écrit que pour le retour vocal.

Est-ce que tu pourras me dire ce qu'il en est, une fois que tu peux appuyer sur le bouton ? Merci

**Comment by jean-luc18** [comment]
Bonjour,

La version v.0.2.1 à réglée tous les problèmes sur android 4.4.2
C'est exactement identique à la version android 6.0.1

**Comment by Oliv4945** [comment]
>La version v.0.2.1 à réglée tous les problèmes sur android 4.4.2

Super, merci du retour.
Pour info je pense que le soucis ne venait pas vraiment de la version d'Android mais de la taille de l'écran.

N'hésites pas si il y a d'autres problèmes
