### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by Oliv4945** [Oliv4945/jarvis-android-app#18]
Thanks to @Falken10 the app is translated in Spanish !
Released as v0.2.3, I send it to Google [Play store](https://play.google.com/store/apps/details?id=net.iopush.jarvis), it should be updated soon.

**Comment by Oliv4945** [comment]
@falken10: Would you mind to translate also the Google Play presentation ?
Thank you for your help !

```
<b>Android application for OpenJarvis</b>
Jarvis.sh is a lightweight configurable multi-lang voice assistant
Meant for home automation running on slow computers (ex: Raspberry Pi)
Installs automatically voice recognition & speech synthesis engines of your choice
Highly extendable thanks to a wide catalog of community plugins.
See OpenJarvis website for more data: <a href="http://domotiquefacile.fr/jarvis/">http://domotiquefacile.fr/jarvis/</a>.

<b>Open source</b>
The application is open source, so you can help by
 * Opening an issue if something is not working: <a href="https://github.com/Oliv4945/jarvis-android-app/issues">https://github.com/Oliv4945/jarvis-android-app/issues</a>
 *  Push some code, see <a href="https://github.com/Oliv4945/jarvis-android-app/">https://github.com/Oliv4945/jarvis-android-app/</a>

<b>Languages</b>
The application currently support English and French, but help is welcomed to translate it in other languages.
```

**Comment by falken10vdl** [comment]
Sure. Please see below the translation to Spanish (Spain locale)
<b>Aplicación Android para OpenJarvis</b>
Jarvis.sh es un asistente de voz ligero, configurable y multi lenguaje pensado para la domótica en ordenadores de recursos limitados (ej: Raspberry Pi).
Instala automáticamente los motores de reconocimiento y síntesis de voz de su elección.
Áltamente extensible gracias al amplio catálogo de "plugins" de la comunidad.
Consulte el sitio web de OpenJarvis. Para más detalles: <a href="http://domotiquefacile.fr/jarvis/">http://domotiquefacile.fr/jarvis/</a>.

<b>Código Abierto</b>
La aplicación es de código abierto, por lo que puede ayudar de las siguientes formas: 
 * Abriendo una incidencia si algo no funciona: <a href="https://github.com/Oliv4945/jarvis-android-app/issues">https://github.com/Oliv4945/jarvis-android-app/issues</a>
 * Subiendo código, ver: <a href="https://github.com/Oliv4945/jarvis-android-app/">https://github.com/Oliv4945/jarvis-android-app/</a>

<b>Idiomas</b>
La aplicación admite actualmente Inglés, Francés y Español pero se agradece la ayuda para traducirla a otros idiomas.

**Comment by falken10vdl** [comment]
Nice, I checked the application in Google Play and it is now translated. I found a little glitch: 
![inkedscreenshot_20171103-083225_li](https://user-images.githubusercontent.com/33285113/32363939-305fa464-c072-11e7-9698-d344a4769017.jpg)
It reads "Preferences" but should say "Preferencias".
Thanks a lot!

**Comment by Oliv4945** [comment]
Hi @falken10,

Thank you for the report, it is now corrected and published on the store :)
