### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by IzzySoft** [Oliv4945/jarvis-android-app#19]
Could you please clarify what license this project uses, @Oliv4945?

**Comment by Oliv4945** [comment]
Sure, I just added [MIT](https://github.com/Oliv4945/jarvis-android-app/blob/master/LICENSE) license, as [Jarvis](https://github.com/alexylem/jarvis/blob/master/LICENSE.md).

**Comment by IzzySoft** [comment]
Great, thanks! I should have thought of checking there…
