### ISSUE TITLE
[170410] App crash on Android 6.0.1 (SAMSUNG Galaxy S5)

### ISSUE THREAD

**Issue by wikijm** [Oliv4945/jarvis-android-app#3]
App crash on Android 6.0.1 (SAMSUNG Galaxy S5) with 170410 version of .apk available [here](https://iopush.net/temp/170412_Jarvis.apk).
[Previous version](https://iopush.net/temp/170410_Jarvis.apk) works like a charm.

Please find attached anonymized log generated with [SysLog app](https://play.google.com/store/apps/details?id=com.tortel.syslog&hl=fr).
[2017-04-13_11.54--s5_6.0.1--logcat.zip](https://github.com/Oliv4945/jarvis-android-app/files/919214/2017-04-13_11.54--s5_6.0.1--logcat.zip)

**Comment by Oliv4945** [comment]
It seems related to a corrupted APK file. I will try to regenerate it this afternoon.

**Comment by wikijm** [comment]
OK with new version, thanks for your time 😃

**Comment by Oliv4945** [comment]
New version, [v0.2.2](https://github.com/Oliv4945/jarvis-android-app/releases/tag/v0.2.2).
