### ISSUE TITLE
Add and force 'http://' on 'URL or IP' field

### ISSUE THREAD

**Issue by wikijm** [Oliv4945/jarvis-android-app#7]
* Phone brand & model: All brand/model
 * Android version: All version
 * Jarvis release: [v0.1.1](https://github.com/Oliv4945/jarvis-android-app/tree/v0.1.1)

Without 'http://' at the beginning of 'URL or IP' field, you'll get an error when trying to use the app.
It must be great to:
- Add 'http://' at the begining
- Check presence of 'http://'

**Comment by Oliv4945** [comment]
Good idea, thanks you !
Now the app add `http://` if required, and a way that will not interfere with people using `https`

It will be in next release, feel free to reopen is it not your idea.

**Comment by Oliv4945** [comment]
[v0.1.2 released](https://github.com/Oliv4945/jarvis-android-app/releases/tag/v0.1.2)
